# full list of rules at: https://github.com/sasstools/sass-lint/tree/develop/docs/rules
options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 1
  # Sample - warn against problematic properties
  # no-disallowed-properties:
  # - 1
  # -
  #  'properties':
  #    - 'z-index'
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  bem-depth:
    - 2
    -
      max-depth: 1

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format:
    - 1
    -
      convention: hyphenatedbem

  class-name-format:
    - 2
    -
      convention: hyphenatedbem

  # Style Guide
  border-zero: 1
  brace-style:
  	- 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation:
    - 2
    -
      size: tab
  leading-zero: 1
  nesting-depth: 1
  # http://rhodesmill.org/brandon/2011/concentric-css/
  property-sort-order:
    - 2
    -
      order:
          # various preceeding rules
        - '@charset'
        - '@import'
        - '@namespace'
        - '@extend'
        - '@variable'
        - '@include'

        # all
        - 'all'

        # position
        - 'display'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        #floats
        - 'float'
        - 'clear'

        # visibility
        - 'visibility'
        - 'z-index'

        # overflow
        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'
        - 'clip'
        - 'zoom'

        # flex
        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'

        # grid
        - 'grid'
        - 'grid-area'
        - 'grid-template'
        - 'grid-template-areas'
        - 'grid-template-rows'
        - 'grid-template-columns'
        - 'grid-row'
        - 'grid-row-start'
        - 'grid-row-end'
        - 'grid-column'
        - 'grid-column-start'
        - 'grid-column-end'
        - 'grid-auto-rows'
        - 'grid-auto-columns'
        - 'grid-auto-flow'
        - 'grid-gap'
        - 'grid-row-gap'
        - 'grid-column-gap'

        #shorthand for align-content and justify-content
        - 'place-content'

        #shorthand for align-items and justify-items
        - 'place-items'

        # align-content
        - 'align-content'
        - 'align-items'
        - 'align-self'

        #justify-content
        - 'justify-content'
        - 'justify-items'
        - 'justify-self'

        # order for flexbox or grid
        - 'order'

        # box-sizing
        - 'box-sizing'

        # width
        - 'width'
        - 'min-width'
        - 'max-width'

        # height
        - 'height'
        - 'min-height'
        - 'max-height'

        # margin
        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        # padding
        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        # tables
        - 'table-layout'
        - 'border-collapse'
        - 'border-spacing'
        - 'empty-cells'

        # columns
        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-rule-width'
        - 'column-rule-style'
        - 'column-rule-color'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        # list-style
        - 'list-style'
        - 'list-style-type'
        - 'list-style-position'
        - 'list-style-image'
        - 'caption-side'

        # content
        - 'content'
        - 'quotes'

        # counters
        - 'counter-reset'
        - 'counter-increment'

        # User Interaction
        - 'resize'
        - 'cursor'
        - 'user-select'

        # animation
        - 'transition'
        - 'transition-delay'
        - 'transition-duration'
        - 'transition-property'
        - 'transition-timing-function'
        - 'transform'
        - 'transform-origin'
        - 'transform-style'
        - '@keyframes'
        - 'animation'
        - 'animation-name'
        - 'animation-duration'
        - 'animation-timing-function'
        - 'animation-delay'
        - 'animation-iteration-count'
        - 'animation-direction'
        - 'animation-fill-mode'
        - 'animation-play-state'
        - 'backface-visibility'
        - 'perspective'
        - 'perspective-origin'

        # text behaviour and styles
        - 'text-align'
        - 'text-align-last'
        - 'vertical-align'
        - 'white-space'
        - 'text-decoration'
        - 'text-decoration-color'
        - 'text-decoration-style'
        - 'text-decoration-line'
        - 'text-emphasis'
        - 'text-emphasis-color'
        - 'text-emphasis-style'
        - 'text-emphasis-position'
        - 'text-indent'
        - 'text-justify'
        - 'text-transform'
        - 'letter-spacing'
        - 'word-spacing'
        - 'text-outline'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-wrap'
        - 'text-overflow'
        - 'text-overflow-ellipsis'
        - 'text-overflow-mode'
        - 'word-wrap'
        - 'word-break'
        - 'tab-size'
        - 'hyphens'
        - 'pointer-events'
        - 'direction'
        - 'unicode-bidi'
        - 'orphans'
        - 'widows'

        # object-fit
        - 'object-fit'
        - 'object-position'

        # opacity and color
        - 'opacity'
        - 'filter'
        - 'color'

        # borders
        - 'border'
        - 'border-collapse'
        - 'border-width'
        - 'border-style'
        - 'border-color'
        - 'border-top'
        - 'border-top-width'
        - 'border-top-style'
        - 'border-top-color'
        - 'border-right'
        - 'border-right-width'
        - 'border-right-style'
        - 'border-right-color'
        - 'border-bottom'
        - 'border-bottom-width'
        - 'border-bottom-style'
        - 'border-bottom-color'
        - 'border-left'
        - 'border-left-width'
        - 'border-left-style'
        - 'border-left-color'

        # border-radius
        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        # border-image
        - 'border-image'
        - 'border-image-source'
        - 'border-image-slice'
        - 'border-image-width'
        - 'border-image-outset'
        - 'border-image-repeat'

        # outline
        - 'outline'
        - 'outline-width'
        - 'outline-style'
        - 'outline-color'
        - 'outline-offset'

        # background
        - 'background'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-attachment'
        - 'background-position'
        - 'background-position-x'
        - 'background-position-y'
        - 'background-clip'
        - 'backgound-origin'
        - 'background-size'

        # box-shadow
        - 'box-decoration-break'
        - 'box-shadow'

        # font
        - 'font'
        - 'font-family'
        - 'src'
        - '@font-feature-values'
        - '@styleset'
        - 'font-size'
        - 'font-size-adjust'
        - 'font-weight'
        - 'font-style'
        - 'font-variant'
        - 'font-stretch'
        - 'font-effect'

        # text-spacing
        - 'line-height'

        # breaks
        - 'page-break-before'
        - 'page-break-after'
        - 'page-break-inside'

        # various subsequent rules
        - '@media'
        - '@supports'
        - '@document'
        - '@page'
        - '@viewport'

  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
